development:
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_PHONE_NUMBER"] %>
production:
  secret_key_base: 4f7557f363bd7e94c0448795a96b6b368801a845500685295da4615da727beea975984d2e120d9c2db012fa1e324655e7265e4cb38516a395e88f0d4470a81ee
  twilio_account_sid: <%= ENV["PROD_TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["PROD_TWILIO_AUTH_TOKEN"] %>
  twilio_phone_number: <%= ENV["PROD_TWILIO_PHONE_NUMBER"] %>
